services:
  - type: web
    name: military-asset-backend
    env: java
    buildCommand: ./mvnw clean package
    startCommand: java -jar target/military-asset-0.0.1-SNAPSHOT.jar
    branch: main
    plan: free
